[GLOBAL]
pants_version = "2.12.0"

backend_packages = [
  # Each backend can be used independently, so there is no need to enable Scala if you
  # have a pure-Java repository (or vice versa).
  "pants.backend.experimental.scala",
]

[jvm.resolves]
cat_req = "3rdparty/jvm/cat.lock"
dog_req = "3rdparty/jvm/dog.lock"

[scala.version_for_resolve]
cat_req = "2.12.15"
dog_req = "2.12.15"

[source]
root_patterns = [
  "/src/*",
  "/tests/*",
]
